#
#       https://github.com/cmhughes/latexindent.pl
#
# for details of how to create and configure your own settings files.

# only one backup per file:
#   - if onlyOneBackUp is 0 then, as a safety measure,
#     the number on the extension increments by 1 each time:
#
#           myfile.bak0, myfile.bak1, myfile.bak2
#   - if you set onlyOnebackUp to 1, then the backup file will
#     be overwritten each time (not recommended until you trust the script)
onlyOneBackUp: 0

# some users may want a finite number of backup files,
# say at most 3; in which case, they can change this maxNumberOfBackUps.
#
# If maxNumberOfBackUps is set to 0 (or less) then infinitely
# many backups are possible, unless onlyOneBackUp is switched on
maxNumberOfBackUps: 0

# preferences for information displayed in the log file
logFilePreferences:
  showEveryYamlRead: 0
  showAmalgamatedSettings: 0
  showDecorationStartCodeBlockTrace: 0
  showDecorationFinishCodeBlockTrace: 0
  showGitHubInfoFooter: 0

# if you want the script to look for \item commands
# and format it, as follows (for example),
#       \begin{itemize}
#           \item content here
#                 next line is indented
#                 next line is indented
#           \item another item
#       \end{itemize}
# then populate indentAfterItems. See also itemNames
indentAfterItems:
  itemize: 1
  enumerate: 1
  description: 1
  list: 1

indentRules:
  myenvironment: ""
  anotherenvironment: ""
  chapter: ""
  section: "\t"
  item: "\t"
  myitem: "\t"

# set noAdditionalIndent globally for codeblocks
# noAdditionalIndentGlobal:
  # UnNamedGroupingBracesBrackets: 1

# you can specify settings on a per-name basis
modifyLineBreaks:
  condenseMultipleBlankLinesInto: 2
  textWrapOptions:
    columns: 80
    perCodeBlockBasis: 1
    tabstop: 2
    all: 1
  removeParagraphLineBreaks:
    all: 1
    beforeTextWrap: 1
